/**
 * 추가 문제 데이터 2 — Track B 실전 도메인 143문제
 */
import { ProblemSpec } from './problems-extra.js'

export const EXTRA_PROBLEMS2: ProblemSpec[] = [

  // ── TRACK B: 이커머스 (21) ──────────────────────────────────────────────────
  {
    title: '브랜드별 평균 상품 가격',
    track: 'case', domain: 'ecommerce', dataset_domain: 'ecommerce', chapter_num: null,
    difficulty: 'easy', grading_mode: 'unordered', tags: ['group_by', 'avg'],
    description: `products 테이블에서 brand별 평균 가격(avg_price)을 구하세요.\n- avg_price는 ROUND(..., 0)\n- avg_price 내림차순 정렬`,
    solution_sql: `SELECT brand, ROUND(AVG(price), 0) AS avg_price FROM products GROUP BY brand ORDER BY avg_price DESC;`,
  },
  {
    title: '재고 부족 상품 목록',
    track: 'case', domain: 'ecommerce', dataset_domain: 'ecommerce', chapter_num: null,
    difficulty: 'easy', grading_mode: 'unordered', tags: ['where', 'order_by'],
    description: `products 테이블에서 stock_qty가 50 미만인 상품의 name, category, stock_qty를 조회하세요.\n- stock_qty 오름차순 정렬`,
    solution_sql: `SELECT name, category, stock_qty FROM products WHERE stock_qty < 50 ORDER BY stock_qty;`,
  },
  {
    title: '도시별 고객 분포',
    track: 'case', domain: 'ecommerce', dataset_domain: 'ecommerce', chapter_num: null,
    difficulty: 'easy', grading_mode: 'unordered', tags: ['group_by', 'count'],
    description: `users 테이블에서 city별 고객 수(user_cnt)를 조회하세요.\n- user_cnt 내림차순 정렬`,
    solution_sql: `SELECT city, COUNT(*) AS user_cnt FROM users GROUP BY city ORDER BY user_cnt DESC;`,
  },
  {
    title: '평점 4점 이상 상품',
    track: 'case', domain: 'ecommerce', dataset_domain: 'ecommerce', chapter_num: null,
    difficulty: 'medium', grading_mode: 'unordered', tags: ['join', 'group_by', 'having'],
    description: `상품별 평균 평점(avg_rating)을 구해 4.0 이상인 상품의 name과 avg_rating을 조회하세요.\n- avg_rating 내림차순 정렬`,
    solution_sql: `SELECT p.name, ROUND(AVG(r.rating), 1) AS avg_rating FROM reviews r JOIN products p ON r.product_id = p.id GROUP BY p.id, p.name HAVING AVG(r.rating) >= 4.0 ORDER BY avg_rating DESC;`,
  },
  {
    title: '상품별 판매 수량 및 매출',
    track: 'case', domain: 'ecommerce', dataset_domain: 'ecommerce', chapter_num: null,
    difficulty: 'medium', grading_mode: 'unordered', tags: ['join', 'group_by', 'sum'],
    description: `order_items와 products를 조인하여 상품별 총 판매 수량(total_qty)과 총 매출(total_revenue)을 조회하세요.\n- total_revenue 내림차순 정렬`,
    solution_sql: `SELECT p.name, SUM(oi.quantity) AS total_qty, SUM(oi.quantity * oi.unit_price) AS total_revenue FROM order_items oi JOIN products p ON oi.product_id = p.id GROUP BY p.id, p.name ORDER BY total_revenue DESC;`,
  },
  {
    title: '주문 상태별 비율',
    track: 'case', domain: 'ecommerce', dataset_domain: 'ecommerce', chapter_num: null,
    difficulty: 'medium', grading_mode: 'unordered', tags: ['group_by', 'arithmetic'],
    description: `orders 테이블에서 status별 주문 건수(cnt)와 전체 대비 비율(pct)을 조회하세요.\n- pct = ROUND(cnt * 100.0 / total, 1)`,
    solution_sql: `SELECT status, COUNT(*) AS cnt, ROUND(COUNT(*) * 100.0 / (SELECT COUNT(*) FROM orders), 1) AS pct FROM orders GROUP BY status ORDER BY cnt DESC;`,
  },
  {
    title: '고객별 마지막 주문일',
    track: 'case', domain: 'ecommerce', dataset_domain: 'ecommerce', chapter_num: null,
    difficulty: 'medium', grading_mode: 'unordered', tags: ['join', 'group_by', 'max'],
    description: `각 고객의 이름(name)과 마지막 주문일(last_order_date)을 조회하세요.\n- last_order_date 최신 순 정렬`,
    solution_sql: `SELECT u.name, MAX(o.created_at) AS last_order_date FROM users u JOIN orders o ON u.id = o.user_id GROUP BY u.id, u.name ORDER BY last_order_date DESC;`,
  },
  {
    title: '평균 주문 금액보다 큰 주문',
    track: 'case', domain: 'ecommerce', dataset_domain: 'ecommerce', chapter_num: null,
    difficulty: 'medium', grading_mode: 'unordered', tags: ['subquery', 'where'],
    description: `completed 상태 주문 중 total_amount가 전체 completed 주문의 평균보다 큰 주문의 id, user_id, total_amount를 조회하세요.\n- total_amount 내림차순 정렬`,
    solution_sql: `SELECT id, user_id, total_amount FROM orders WHERE status = 'completed' AND total_amount > (SELECT AVG(total_amount) FROM orders WHERE status = 'completed') ORDER BY total_amount DESC;`,
  },
  {
    title: '카테고리별 재고 부족 상품 수',
    track: 'case', domain: 'ecommerce', dataset_domain: 'ecommerce', chapter_num: null,
    difficulty: 'medium', grading_mode: 'unordered', tags: ['group_by', 'where', 'count'],
    description: `stock_qty가 50 미만인 상품을 category별로 집계하여 부족 상품 수(low_stock_cnt)를 조회하세요.`,
    solution_sql: `SELECT category, COUNT(*) AS low_stock_cnt FROM products WHERE stock_qty < 50 GROUP BY category ORDER BY low_stock_cnt DESC;`,
  },
  {
    title: '날짜별 주문 건수 추이',
    track: 'case', domain: 'ecommerce', dataset_domain: 'ecommerce', chapter_num: null,
    difficulty: 'medium', grading_mode: 'ordered', tags: ['group_by', 'date'],
    description: `orders 테이블에서 날짜(DATE(created_at))별 주문 건수(order_cnt)를 조회하세요.\n- 날짜 오름차순 정렬`,
    solution_sql: `SELECT DATE(created_at) AS date, COUNT(*) AS order_cnt FROM orders GROUP BY date ORDER BY date;`,
  },
  {
    title: '한 번만 구매한 고객',
    track: 'case', domain: 'ecommerce', dataset_domain: 'ecommerce', chapter_num: null,
    difficulty: 'medium', grading_mode: 'unordered', tags: ['group_by', 'having', 'join'],
    description: `completed 주문이 정확히 1건인 고객의 name과 주문 횟수(order_cnt)를 조회하세요.`,
    solution_sql: `SELECT u.name, COUNT(*) AS order_cnt FROM orders o JOIN users u ON o.user_id = u.id WHERE o.status = 'completed' GROUP BY u.id, u.name HAVING COUNT(*) = 1;`,
  },
  {
    title: '리뷰 없는 상품',
    track: 'case', domain: 'ecommerce', dataset_domain: 'ecommerce', chapter_num: null,
    difficulty: 'medium', grading_mode: 'unordered', tags: ['left_join', 'null'],
    description: `리뷰가 하나도 없는 상품의 name과 category를 조회하세요.\n- LEFT JOIN + IS NULL 활용`,
    solution_sql: `SELECT p.name, p.category FROM products p LEFT JOIN reviews r ON p.id = r.product_id WHERE r.id IS NULL ORDER BY p.name;`,
  },
  {
    title: '별점 분포',
    track: 'case', domain: 'ecommerce', dataset_domain: 'ecommerce', chapter_num: null,
    difficulty: 'easy', grading_mode: 'ordered', tags: ['group_by', 'count'],
    description: `reviews 테이블에서 rating별 리뷰 수(cnt)를 조회하세요.\n- rating 오름차순 정렬`,
    solution_sql: `SELECT rating, COUNT(*) AS cnt FROM reviews GROUP BY rating ORDER BY rating;`,
  },
  {
    title: '완료 주문 최고액 TOP 5',
    track: 'case', domain: 'ecommerce', dataset_domain: 'ecommerce', chapter_num: null,
    difficulty: 'easy', grading_mode: 'ordered', tags: ['join', 'order_by', 'limit'],
    description: `completed 주문 중 total_amount 기준 TOP 5의 고객 이름(name), 주문 금액(total_amount), 주문일(created_at)을 조회하세요.`,
    solution_sql: `SELECT u.name, o.total_amount, o.created_at FROM orders o JOIN users u ON o.user_id = u.id WHERE o.status = 'completed' ORDER BY o.total_amount DESC LIMIT 5;`,
  },
  {
    title: '도시별 총 매출',
    track: 'case', domain: 'ecommerce', dataset_domain: 'ecommerce', chapter_num: null,
    difficulty: 'medium', grading_mode: 'unordered', tags: ['join', 'group_by', 'sum'],
    description: `고객의 city별 총 구매액(city_revenue)을 구하세요.\n- completed 주문만\n- city_revenue 내림차순 정렬`,
    solution_sql: `SELECT u.city, SUM(o.total_amount) AS city_revenue FROM orders o JOIN users u ON o.user_id = u.id WHERE o.status = 'completed' GROUP BY u.city ORDER BY city_revenue DESC;`,
  },
  {
    title: '카테고리 내 최고 평점 상품',
    track: 'case', domain: 'ecommerce', dataset_domain: 'ecommerce', chapter_num: null,
    difficulty: 'hard', grading_mode: 'unordered', tags: ['window', 'rank', 'join'],
    description: `카테고리별로 평균 평점(avg_rating)이 가장 높은 상품의 name, category, avg_rating을 조회하세요.\n- 리뷰가 없는 상품 제외\n- RANK() 윈도우 함수 활용`,
    solution_sql: `WITH rated AS (SELECT p.name, p.category, ROUND(AVG(r.rating), 1) AS avg_rating, RANK() OVER (PARTITION BY p.category ORDER BY AVG(r.rating) DESC) AS rnk FROM reviews r JOIN products p ON r.product_id = p.id GROUP BY p.id, p.name, p.category) SELECT name, category, avg_rating FROM rated WHERE rnk = 1;`,
  },
  {
    title: '비용 대비 매출 효율 분석',
    track: 'case', domain: 'ecommerce', dataset_domain: 'ecommerce', chapter_num: null,
    difficulty: 'hard', grading_mode: 'unordered', tags: ['join', 'group_by', 'arithmetic'],
    description: `카테고리별 총 원가(total_cost), 총 매출(total_revenue), 총마진율(gross_margin_pct)을 계산하세요.\n- gross_margin_pct = ROUND((total_revenue - total_cost) * 100.0 / total_revenue, 1)\n- gross_margin_pct 내림차순 정렬`,
    solution_sql: `SELECT p.category, SUM(oi.quantity * p.cost_price) AS total_cost, SUM(oi.quantity * oi.unit_price) AS total_revenue, ROUND((SUM(oi.quantity * oi.unit_price) - SUM(oi.quantity * p.cost_price)) * 100.0 / SUM(oi.quantity * oi.unit_price), 1) AS gross_margin_pct FROM order_items oi JOIN products p ON oi.product_id = p.id GROUP BY p.category ORDER BY gross_margin_pct DESC;`,
  },
  {
    title: 'order_items 없는 주문',
    track: 'case', domain: 'ecommerce', dataset_domain: 'ecommerce', chapter_num: null,
    difficulty: 'medium', grading_mode: 'unordered', tags: ['left_join', 'null'],
    description: `order_items가 하나도 없는 주문의 id, user_id, status를 조회하세요.`,
    solution_sql: `SELECT o.id, o.user_id, o.status FROM orders o LEFT JOIN order_items oi ON o.id = oi.order_id WHERE oi.id IS NULL;`,
  },
  {
    title: '상품 판매 순위',
    track: 'case', domain: 'ecommerce', dataset_domain: 'ecommerce', chapter_num: null,
    difficulty: 'hard', grading_mode: 'ordered', tags: ['window', 'rank', 'join'],
    description: `상품별 총 판매 수량(total_qty)을 집계하고 RANK() 함수로 순위(sales_rank)를 매겨 name, total_qty, sales_rank를 조회하세요.`,
    solution_sql: `WITH sales AS (SELECT p.name, SUM(oi.quantity) AS total_qty FROM order_items oi JOIN products p ON oi.product_id = p.id GROUP BY p.id, p.name) SELECT name, total_qty, RANK() OVER (ORDER BY total_qty DESC) AS sales_rank FROM sales ORDER BY sales_rank;`,
  },
  {
    title: '등급별 평균 주문 금액',
    track: 'case', domain: 'ecommerce', dataset_domain: 'ecommerce', chapter_num: null,
    difficulty: 'medium', grading_mode: 'unordered', tags: ['join', 'group_by', 'avg'],
    description: `고객 grade별 평균 주문 금액(avg_order_amount)을 조회하세요.\n- completed 주문만\n- avg_order_amount 내림차순 정렬`,
    solution_sql: `SELECT u.grade, ROUND(AVG(o.total_amount), 0) AS avg_order_amount FROM orders o JOIN users u ON o.user_id = u.id WHERE o.status = 'completed' GROUP BY u.grade ORDER BY avg_order_amount DESC;`,
  },
  {
    title: '월별 환불/취소 건수',
    track: 'case', domain: 'ecommerce', dataset_domain: 'ecommerce', chapter_num: null,
    difficulty: 'medium', grading_mode: 'ordered', tags: ['group_by', 'date', 'where'],
    description: `status가 'refunded' 또는 'cancelled'인 주문을 월별로 집계하여 건수(cancel_cnt)를 조회하세요.\n- 최신 월 순 정렬`,
    solution_sql: `SELECT STRFTIME('%Y-%m', created_at) AS month, COUNT(*) AS cancel_cnt FROM orders WHERE status IN ('refunded', 'cancelled') GROUP BY month ORDER BY month DESC;`,
  },

  // ── TRACK B: SaaS (21) ─────────────────────────────────────────────────────
  {
    title: '기업 규모별 MRR 분포',
    track: 'case', domain: 'saas', dataset_domain: 'saas', chapter_num: null,
    difficulty: 'medium', grading_mode: 'unordered', tags: ['case', 'group_by', 'sum'],
    description: `companies 테이블에서 employee_cnt 기준으로 '소규모'(<10), '중규모'(<50), '대규모'(50 이상)로 구분하여 기업 수(cnt)와 총 MRR(total_mrr)을 조회하세요.\n- churned_at IS NULL인 기업만`,
    solution_sql: `SELECT CASE WHEN employee_cnt < 10 THEN '소규모' WHEN employee_cnt < 50 THEN '중규모' ELSE '대규모' END AS size_group, COUNT(*) AS cnt, SUM(mrr) AS total_mrr FROM companies WHERE churned_at IS NULL GROUP BY size_group ORDER BY total_mrr DESC;`,
  },
  {
    title: '국가별 기업 수',
    track: 'case', domain: 'saas', dataset_domain: 'saas', chapter_num: null,
    difficulty: 'easy', grading_mode: 'unordered', tags: ['group_by', 'count'],
    description: `companies 테이블에서 country별 기업 수(company_cnt)를 조회하세요.\n- company_cnt 내림차순 정렬`,
    solution_sql: `SELECT country, COUNT(*) AS company_cnt FROM companies GROUP BY country ORDER BY company_cnt DESC;`,
  },
  {
    title: '이벤트 유형별 건수',
    track: 'case', domain: 'saas', dataset_domain: 'saas', chapter_num: null,
    difficulty: 'easy', grading_mode: 'unordered', tags: ['group_by', 'count'],
    description: `events 테이블에서 event_name별 발생 건수(cnt)를 조회하세요.\n- cnt 내림차순 정렬`,
    solution_sql: `SELECT event_name, COUNT(*) AS cnt FROM events GROUP BY event_name ORDER BY cnt DESC;`,
  },
  {
    title: '유저 역할별 분포',
    track: 'case', domain: 'saas', dataset_domain: 'saas', chapter_num: null,
    difficulty: 'easy', grading_mode: 'unordered', tags: ['group_by', 'count'],
    description: `users 테이블에서 role별 유저 수(cnt)를 조회하세요.`,
    solution_sql: `SELECT role, COUNT(*) AS cnt FROM users GROUP BY role ORDER BY cnt DESC;`,
  },
  {
    title: '플랜별 평균 MRR',
    track: 'case', domain: 'saas', dataset_domain: 'saas', chapter_num: null,
    difficulty: 'easy', grading_mode: 'unordered', tags: ['group_by', 'avg'],
    description: `churned_at IS NULL인 기업의 plan별 평균 MRR(avg_mrr)을 조회하세요.\n- avg_mrr 내림차순 정렬`,
    solution_sql: `SELECT plan, ROUND(AVG(mrr), 0) AS avg_mrr FROM companies WHERE churned_at IS NULL GROUP BY plan ORDER BY avg_mrr DESC;`,
  },
  {
    title: '산업별 기업 수 및 총 MRR',
    track: 'case', domain: 'saas', dataset_domain: 'saas', chapter_num: null,
    difficulty: 'medium', grading_mode: 'unordered', tags: ['group_by', 'sum'],
    description: `churned_at IS NULL인 기업의 industry별 기업 수(company_cnt)와 총 MRR(total_mrr)을 조회하세요.\n- total_mrr 내림차순 정렬`,
    solution_sql: `SELECT industry, COUNT(*) AS company_cnt, SUM(mrr) AS total_mrr FROM companies WHERE churned_at IS NULL GROUP BY industry ORDER BY total_mrr DESC;`,
  },
  {
    title: '구독 billing_cycle별 현황',
    track: 'case', domain: 'saas', dataset_domain: 'saas', chapter_num: null,
    difficulty: 'easy', grading_mode: 'unordered', tags: ['group_by', 'count', 'avg'],
    description: `subscriptions 테이블에서 billing_cycle별 구독 수(sub_cnt)와 평균 구독 금액(avg_amount)을 조회하세요.`,
    solution_sql: `SELECT billing_cycle, COUNT(*) AS sub_cnt, ROUND(AVG(amount), 0) AS avg_amount FROM subscriptions GROUP BY billing_cycle ORDER BY sub_cnt DESC;`,
  },
  {
    title: '이벤트 가장 많이 발생한 날 TOP 5',
    track: 'case', domain: 'saas', dataset_domain: 'saas', chapter_num: null,
    difficulty: 'medium', grading_mode: 'ordered', tags: ['group_by', 'date', 'order_by'],
    description: `events 테이블에서 날짜(DATE(created_at))별 이벤트 건수(event_cnt)를 집계하여 상위 5일을 조회하세요.`,
    solution_sql: `SELECT DATE(created_at) AS date, COUNT(*) AS event_cnt FROM events GROUP BY date ORDER BY event_cnt DESC LIMIT 5;`,
  },
  {
    title: '가장 많이 로그인한 유저 TOP 5',
    track: 'case', domain: 'saas', dataset_domain: 'saas', chapter_num: null,
    difficulty: 'medium', grading_mode: 'ordered', tags: ['join', 'group_by', 'order_by'],
    description: `event_name = 'login'인 이벤트를 집계하여 로그인 횟수(login_cnt)가 가장 많은 유저 TOP 5의 name과 login_cnt를 조회하세요.`,
    solution_sql: `SELECT u.name, COUNT(*) AS login_cnt FROM events e JOIN users u ON e.user_id = u.id WHERE e.event_name = 'login' GROUP BY u.id, u.name ORDER BY login_cnt DESC LIMIT 5;`,
  },
  {
    title: '기업별 관리자 수',
    track: 'case', domain: 'saas', dataset_domain: 'saas', chapter_num: null,
    difficulty: 'medium', grading_mode: 'unordered', tags: ['join', 'group_by', 'where'],
    description: `role = 'admin'인 유저를 기업별로 집계하여 기업명(company name)과 admin_cnt를 조회하세요.\n- admin_cnt 내림차순 정렬`,
    solution_sql: `SELECT c.name, COUNT(*) AS admin_cnt FROM users u JOIN companies c ON u.company_id = c.id WHERE u.role = 'admin' GROUP BY c.id, c.name ORDER BY admin_cnt DESC;`,
  },
  {
    title: '높은 MRR 기업 TOP 5',
    track: 'case', domain: 'saas', dataset_domain: 'saas', chapter_num: null,
    difficulty: 'easy', grading_mode: 'ordered', tags: ['order_by', 'limit'],
    description: `churned_at IS NULL인 기업 중 mrr 기준 TOP 5의 name, plan, mrr을 조회하세요.`,
    solution_sql: `SELECT name, plan, mrr FROM companies WHERE churned_at IS NULL ORDER BY mrr DESC LIMIT 5;`,
  },
  {
    title: '로그인 없는 유저 목록',
    track: 'case', domain: 'saas', dataset_domain: 'saas', chapter_num: null,
    difficulty: 'medium', grading_mode: 'unordered', tags: ['join', 'where', 'null'],
    description: `last_login이 NULL인 유저의 name, email, 기업명(company name)을 조회하세요.`,
    solution_sql: `SELECT u.name, u.email, c.name AS company_name FROM users u JOIN companies c ON u.company_id = c.id WHERE u.last_login IS NULL ORDER BY u.name;`,
  },
  {
    title: '가장 많이 방문된 페이지 TOP 5',
    track: 'case', domain: 'saas', dataset_domain: 'saas', chapter_num: null,
    difficulty: 'medium', grading_mode: 'ordered', tags: ['group_by', 'where', 'order_by'],
    description: `event_name = 'page_view'인 이벤트에서 page별 방문 수(visit_cnt) 상위 5개를 조회하세요.`,
    solution_sql: `SELECT page, COUNT(*) AS visit_cnt FROM events WHERE event_name = 'page_view' GROUP BY page ORDER BY visit_cnt DESC LIMIT 5;`,
  },
  {
    title: '현재 활성 구독 기업 목록',
    track: 'case', domain: 'saas', dataset_domain: 'saas', chapter_num: null,
    difficulty: 'medium', grading_mode: 'unordered', tags: ['join', 'where', 'null'],
    description: `ended_at이 NULL인 구독이 있는 기업의 name, plan, 구독 금액(amount)을 조회하세요.\n- amount 내림차순 정렬`,
    solution_sql: `SELECT c.name, c.plan, s.amount FROM companies c JOIN subscriptions s ON c.id = s.company_id WHERE s.ended_at IS NULL ORDER BY s.amount DESC;`,
  },
  {
    title: '기능 사용(feature_use) 가장 많이 한 기업 TOP 5',
    track: 'case', domain: 'saas', dataset_domain: 'saas', chapter_num: null,
    difficulty: 'hard', grading_mode: 'ordered', tags: ['join', 'group_by', 'order_by'],
    description: `event_name = 'feature_use'인 이벤트를 기업별로 집계하여 기업명(company name)과 feature_use_cnt 기준 TOP 5를 조회하세요.`,
    solution_sql: `SELECT c.name, COUNT(*) AS feature_use_cnt FROM events e JOIN users u ON e.user_id = u.id JOIN companies c ON u.company_id = c.id WHERE e.event_name = 'feature_use' GROUP BY c.id, c.name ORDER BY feature_use_cnt DESC LIMIT 5;`,
  },
  {
    title: '유저당 평균 이벤트 수',
    track: 'case', domain: 'saas', dataset_domain: 'saas', chapter_num: null,
    difficulty: 'medium', grading_mode: 'unordered', tags: ['join', 'group_by', 'avg'],
    description: `유저별 이벤트 수(event_cnt)를 구하고, 전체 유저의 평균 이벤트 수(avg_events_per_user)를 조회하세요.`,
    solution_sql: `WITH user_events AS (SELECT u.id, COUNT(e.id) AS event_cnt FROM users u LEFT JOIN events e ON u.id = e.user_id GROUP BY u.id) SELECT ROUND(AVG(event_cnt), 1) AS avg_events_per_user FROM user_events;`,
  },
  {
    title: '플랜별 이탈률',
    track: 'case', domain: 'saas', dataset_domain: 'saas', chapter_num: null,
    difficulty: 'hard', grading_mode: 'unordered', tags: ['group_by', 'case', 'arithmetic'],
    description: `plan별 전체 기업 수(total_cnt), 이탈 기업 수(churned_cnt), 이탈률(churn_rate_pct)을 조회하세요.\n- churn_rate_pct = ROUND(churned_cnt * 100.0 / total_cnt, 1)`,
    solution_sql: `SELECT plan, COUNT(*) AS total_cnt, SUM(CASE WHEN churned_at IS NOT NULL THEN 1 ELSE 0 END) AS churned_cnt, ROUND(SUM(CASE WHEN churned_at IS NOT NULL THEN 1 ELSE 0 END) * 100.0 / COUNT(*), 1) AS churn_rate_pct FROM companies GROUP BY plan ORDER BY churn_rate_pct DESC;`,
  },
  {
    title: '구독 업그레이드 경험 기업',
    track: 'case', domain: 'saas', dataset_domain: 'saas', chapter_num: null,
    difficulty: 'hard', grading_mode: 'unordered', tags: ['subquery', 'join'],
    description: `'starter' 구독 이력이 있으면서 'growth' 또는 'enterprise' 구독 이력도 있는 기업의 name을 조회하세요.`,
    solution_sql: `SELECT DISTINCT c.name FROM companies c WHERE c.id IN (SELECT company_id FROM subscriptions WHERE plan = 'starter') AND c.id IN (SELECT company_id FROM subscriptions WHERE plan IN ('growth', 'enterprise')) ORDER BY c.name;`,
  },
  {
    title: '기업당 총 구독 기간',
    track: 'case', domain: 'saas', dataset_domain: 'saas', chapter_num: null,
    difficulty: 'hard', grading_mode: 'unordered', tags: ['join', 'group_by', 'date'],
    description: `기업별로 모든 구독의 총 기간(total_days)을 합산하세요.\n- total_days = SUM(JULIANDAY(COALESCE(ended_at, '2024-03-20')) - JULIANDAY(started_at))\n- 기업명(company name), total_days 출력\n- total_days 내림차순`,
    solution_sql: `SELECT c.name, ROUND(SUM(JULIANDAY(COALESCE(s.ended_at, '2024-03-20')) - JULIANDAY(s.started_at)), 0) AS total_days FROM subscriptions s JOIN companies c ON s.company_id = c.id GROUP BY c.id, c.name ORDER BY total_days DESC;`,
  },
  {
    title: '미활성 유저 비율',
    track: 'case', domain: 'saas', dataset_domain: 'saas', chapter_num: null,
    difficulty: 'medium', grading_mode: 'unordered', tags: ['case', 'arithmetic'],
    description: `전체 유저 중 last_login이 '2024-02-01' 이전이거나 NULL인 유저 수(inactive_cnt), 전체 유저 수(total_cnt), 미활성 비율(inactive_pct)을 조회하세요.`,
    solution_sql: `SELECT COUNT(*) AS total_cnt, SUM(CASE WHEN last_login < '2024-02-01' OR last_login IS NULL THEN 1 ELSE 0 END) AS inactive_cnt, ROUND(SUM(CASE WHEN last_login < '2024-02-01' OR last_login IS NULL THEN 1 ELSE 0 END) * 100.0 / COUNT(*), 1) AS inactive_pct FROM users;`,
  },
  {
    title: '가입 월별 기업 등록 수',
    track: 'case', domain: 'saas', dataset_domain: 'saas', chapter_num: null,
    difficulty: 'medium', grading_mode: 'ordered', tags: ['group_by', 'date'],
    description: `companies 테이블에서 연도-월별 신규 등록 기업 수(new_companies)를 조회하세요.\n- created_at 기준, 최신 월 순 정렬`,
    solution_sql: `SELECT STRFTIME('%Y-%m', created_at) AS month, COUNT(*) AS new_companies FROM companies GROUP BY month ORDER BY month DESC;`,
  },

  // ── TRACK B: 핀테크 (21) ────────────────────────────────────────────────────
  {
    title: 'KYC 상태별 유저 수',
    track: 'case', domain: 'fintech', dataset_domain: 'fintech', chapter_num: null,
    difficulty: 'easy', grading_mode: 'unordered', tags: ['group_by', 'count'],
    description: `users 테이블에서 kyc_status별 유저 수(user_cnt)를 조회하세요.\n- user_cnt 내림차순 정렬`,
    solution_sql: `SELECT kyc_status, COUNT(*) AS user_cnt FROM users GROUP BY kyc_status ORDER BY user_cnt DESC;`,
  },
  {
    title: '카드 유형별 발급 수',
    track: 'case', domain: 'fintech', dataset_domain: 'fintech', chapter_num: null,
    difficulty: 'easy', grading_mode: 'unordered', tags: ['group_by', 'count'],
    description: `cards 테이블에서 card_type별 발급 수(cnt)를 조회하세요.`,
    solution_sql: `SELECT card_type, COUNT(*) AS cnt FROM cards GROUP BY card_type ORDER BY cnt DESC;`,
  },
  {
    title: '거래 유형별 평균 금액',
    track: 'case', domain: 'fintech', dataset_domain: 'fintech', chapter_num: null,
    difficulty: 'easy', grading_mode: 'unordered', tags: ['group_by', 'avg'],
    description: `completed 상태인 거래의 type별 평균 금액(avg_amount)과 건수(cnt)를 조회하세요.\n- avg_amount 내림차순 정렬`,
    solution_sql: `SELECT type, ROUND(AVG(amount), 0) AS avg_amount, COUNT(*) AS cnt FROM transactions WHERE status = 'completed' GROUP BY type ORDER BY avg_amount DESC;`,
  },
  {
    title: '계좌 유형별 총 잔액',
    track: 'case', domain: 'fintech', dataset_domain: 'fintech', chapter_num: null,
    difficulty: 'easy', grading_mode: 'unordered', tags: ['group_by', 'sum'],
    description: `active 상태 계좌의 type별 계좌 수(account_cnt)와 총 잔액(total_balance)을 조회하세요.`,
    solution_sql: `SELECT type, COUNT(*) AS account_cnt, SUM(balance) AS total_balance FROM accounts WHERE status = 'active' GROUP BY type ORDER BY total_balance DESC;`,
  },
  {
    title: '동결 계좌 현황',
    track: 'case', domain: 'fintech', dataset_domain: 'fintech', chapter_num: null,
    difficulty: 'medium', grading_mode: 'unordered', tags: ['join', 'where'],
    description: `status = 'frozen'인 계좌의 유저 이름(name), 계좌 유형(type), 잔액(balance)을 조회하세요.\n- balance 내림차순 정렬`,
    solution_sql: `SELECT u.name, a.type, a.balance FROM accounts a JOIN users u ON a.user_id = u.id WHERE a.status = 'frozen' ORDER BY a.balance DESC;`,
  },
  {
    title: '거래 건수 가장 많은 계좌 TOP 5',
    track: 'case', domain: 'fintech', dataset_domain: 'fintech', chapter_num: null,
    difficulty: 'medium', grading_mode: 'ordered', tags: ['join', 'group_by', 'order_by'],
    description: `계좌별 거래 건수(txn_cnt)를 집계하여 TOP 5의 계좌 id, 유형(type), 유저 이름(name), txn_cnt를 조회하세요.`,
    solution_sql: `SELECT a.id, a.type, u.name, COUNT(t.id) AS txn_cnt FROM transactions t JOIN accounts a ON t.account_id = a.id JOIN users u ON a.user_id = u.id GROUP BY a.id, a.type, u.name ORDER BY txn_cnt DESC LIMIT 5;`,
  },
  {
    title: '카테고리별 평균 결제 금액',
    track: 'case', domain: 'fintech', dataset_domain: 'fintech', chapter_num: null,
    difficulty: 'medium', grading_mode: 'unordered', tags: ['group_by', 'where', 'avg'],
    description: `type = 'payment', status = 'completed'인 거래의 category별 평균 금액(avg_amount)과 건수(txn_cnt)를 조회하세요.\n- avg_amount 내림차순 정렬`,
    solution_sql: `SELECT category, ROUND(AVG(amount), 0) AS avg_amount, COUNT(*) AS txn_cnt FROM transactions WHERE type = 'payment' AND status = 'completed' GROUP BY category ORDER BY avg_amount DESC;`,
  },
  {
    title: '펜딩 거래 현황',
    track: 'case', domain: 'fintech', dataset_domain: 'fintech', chapter_num: null,
    difficulty: 'medium', grading_mode: 'unordered', tags: ['join', 'where'],
    description: `status = 'pending'인 거래의 유저 이름(name), 거래 유형(type), 금액(amount), 거래일(created_at)을 조회하세요.\n- amount 내림차순 정렬`,
    solution_sql: `SELECT u.name, t.type, t.amount, t.created_at FROM transactions t JOIN accounts a ON t.account_id = a.id JOIN users u ON a.user_id = u.id WHERE t.status = 'pending' ORDER BY t.amount DESC;`,
  },
  {
    title: '거래 없는 계좌',
    track: 'case', domain: 'fintech', dataset_domain: 'fintech', chapter_num: null,
    difficulty: 'medium', grading_mode: 'unordered', tags: ['left_join', 'null'],
    description: `거래 내역이 하나도 없는 계좌의 id, 유형(type), 잔액(balance), 유저 이름(name)을 조회하세요.`,
    solution_sql: `SELECT a.id, a.type, a.balance, u.name FROM accounts a JOIN users u ON a.user_id = u.id LEFT JOIN transactions t ON a.id = t.account_id WHERE t.id IS NULL ORDER BY a.balance DESC;`,
  },
  {
    title: '유저별 계좌 수',
    track: 'case', domain: 'fintech', dataset_domain: 'fintech', chapter_num: null,
    difficulty: 'medium', grading_mode: 'unordered', tags: ['join', 'group_by', 'count'],
    description: `유저별 보유 계좌 수(account_cnt)를 조회하세요.\n- name, account_cnt 출력\n- account_cnt 내림차순 정렬`,
    solution_sql: `SELECT u.name, COUNT(a.id) AS account_cnt FROM users u LEFT JOIN accounts a ON u.id = a.user_id GROUP BY u.id, u.name ORDER BY account_cnt DESC;`,
  },
  {
    title: '입금 상위 5일 분석',
    track: 'case', domain: 'fintech', dataset_domain: 'fintech', chapter_num: null,
    difficulty: 'medium', grading_mode: 'ordered', tags: ['group_by', 'date', 'where'],
    description: `type = 'deposit', status = 'completed'인 거래를 날짜(DATE(created_at))별로 집계하여 총 입금액(total_deposit) 기준 TOP 5 날짜를 조회하세요.`,
    solution_sql: `SELECT DATE(created_at) AS date, SUM(amount) AS total_deposit FROM transactions WHERE type = 'deposit' AND status = 'completed' GROUP BY date ORDER BY total_deposit DESC LIMIT 5;`,
  },
  {
    title: '식비 vs 쇼핑 지출 비교',
    track: 'case', domain: 'fintech', dataset_domain: 'fintech', chapter_num: null,
    difficulty: 'medium', grading_mode: 'unordered', tags: ['case', 'sum'],
    description: `type = 'payment', status = 'completed'인 거래에서 food 카테고리 총 지출(food_spend)과 shopping 카테고리 총 지출(shopping_spend)을 한 행으로 조회하세요.`,
    solution_sql: `SELECT SUM(CASE WHEN category = 'food' THEN amount ELSE 0 END) AS food_spend, SUM(CASE WHEN category = 'shopping' THEN amount ELSE 0 END) AS shopping_spend FROM transactions WHERE type = 'payment' AND status = 'completed';`,
  },
  {
    title: '최근 입금 TOP 5 유저',
    track: 'case', domain: 'fintech', dataset_domain: 'fintech', chapter_num: null,
    difficulty: 'medium', grading_mode: 'ordered', tags: ['join', 'group_by', 'order_by'],
    description: `type = 'deposit', status = 'completed'인 거래를 유저별로 집계하여 총 입금액(total_deposit) TOP 5의 name과 total_deposit을 조회하세요.`,
    solution_sql: `SELECT u.name, SUM(t.amount) AS total_deposit FROM transactions t JOIN accounts a ON t.account_id = a.id JOIN users u ON a.user_id = u.id WHERE t.type = 'deposit' AND t.status = 'completed' GROUP BY u.id, u.name ORDER BY total_deposit DESC LIMIT 5;`,
  },
  {
    title: '미인증(KYC pending) 유저 잔액 합계',
    track: 'case', domain: 'fintech', dataset_domain: 'fintech', chapter_num: null,
    difficulty: 'medium', grading_mode: 'unordered', tags: ['join', 'where', 'sum'],
    description: `kyc_status = 'pending'인 유저의 active 계좌 잔액 합계(total_pending_balance)를 조회하세요.`,
    solution_sql: `SELECT SUM(a.balance) AS total_pending_balance FROM accounts a JOIN users u ON a.user_id = u.id WHERE u.kyc_status = 'pending' AND a.status = 'active';`,
  },
  {
    title: '월별 거래 총액 추이',
    track: 'case', domain: 'fintech', dataset_domain: 'fintech', chapter_num: null,
    difficulty: 'medium', grading_mode: 'ordered', tags: ['group_by', 'date', 'sum'],
    description: `status = 'completed'인 거래를 연도-월별로 집계하여 총 거래 금액(total_amount)과 건수(txn_cnt)를 조회하세요.\n- 최신 월 순 정렬`,
    solution_sql: `SELECT STRFTIME('%Y-%m', created_at) AS month, SUM(amount) AS total_amount, COUNT(*) AS txn_cnt FROM transactions WHERE status = 'completed' GROUP BY month ORDER BY month DESC;`,
  },
  {
    title: '잔액 대비 총 지출 비율',
    track: 'case', domain: 'fintech', dataset_domain: 'fintech', chapter_num: null,
    difficulty: 'hard', grading_mode: 'unordered', tags: ['join', 'group_by', 'arithmetic'],
    description: `active 계좌를 보유한 유저별로 현재 총 잔액(total_balance)과 총 결제 지출(total_payment)을 구해, 잔액 대비 지출 비율(spend_ratio)을 조회하세요.\n- spend_ratio = ROUND(total_payment * 100.0 / NULLIF(total_balance, 0), 1)\n- spend_ratio 내림차순 정렬`,
    solution_sql: `WITH user_balance AS (SELECT a.user_id, SUM(a.balance) AS total_balance FROM accounts a WHERE a.status = 'active' GROUP BY a.user_id), user_spend AS (SELECT a.user_id, SUM(t.amount) AS total_payment FROM transactions t JOIN accounts a ON t.account_id = a.id WHERE t.type = 'payment' AND t.status = 'completed' GROUP BY a.user_id) SELECT u.name, ub.total_balance, COALESCE(us.total_payment, 0) AS total_payment, ROUND(COALESCE(us.total_payment, 0) * 100.0 / NULLIF(ub.total_balance, 0), 1) AS spend_ratio FROM users u JOIN user_balance ub ON u.id = ub.user_id LEFT JOIN user_spend us ON u.id = us.user_id ORDER BY spend_ratio DESC;`,
  },
  {
    title: '카드 한도 초과 분석',
    track: 'case', domain: 'fintech', dataset_domain: 'fintech', chapter_num: null,
    difficulty: 'hard', grading_mode: 'unordered', tags: ['join', 'group_by', 'having'],
    description: `2024년 3월 한 달간 카드별 결제 금액 합계가 monthly_limit을 초과한 카드의 유저 이름(name), card_type, monthly_limit, 3월 결제 합계(march_spend)를 조회하세요.`,
    solution_sql: `SELECT u.name, c.card_type, c.monthly_limit, SUM(t.amount) AS march_spend FROM cards c JOIN accounts a ON c.account_id = a.id JOIN users u ON a.user_id = u.id JOIN transactions t ON a.id = t.account_id WHERE c.status = 'active' AND t.type = 'payment' AND t.status = 'completed' AND t.created_at LIKE '2024-03-%' GROUP BY c.id, u.name, c.card_type, c.monthly_limit HAVING SUM(t.amount) > c.monthly_limit ORDER BY march_spend DESC;`,
  },
  {
    title: '계좌 개설 월별 집계',
    track: 'case', domain: 'fintech', dataset_domain: 'fintech', chapter_num: null,
    difficulty: 'medium', grading_mode: 'ordered', tags: ['group_by', 'date'],
    description: `accounts 테이블에서 연도-월별 개설 계좌 수(new_accounts)를 조회하세요.\n- created_at 기준, 최신 월 순 정렬`,
    solution_sql: `SELECT STRFTIME('%Y-%m', created_at) AS month, COUNT(*) AS new_accounts FROM accounts GROUP BY month ORDER BY month DESC;`,
  },
  {
    title: '이체(transfer) 현황',
    track: 'case', domain: 'fintech', dataset_domain: 'fintech', chapter_num: null,
    difficulty: 'medium', grading_mode: 'unordered', tags: ['join', 'where', 'sum'],
    description: `type = 'transfer', status = 'completed'인 거래의 총 이체 금액(total_transfer)과 건수(transfer_cnt)를 조회하세요.`,
    solution_sql: `SELECT COUNT(*) AS transfer_cnt, SUM(amount) AS total_transfer FROM transactions WHERE type = 'transfer' AND status = 'completed';`,
  },
  {
    title: 'balance_after 기준 최고 잔액 기록',
    track: 'case', domain: 'fintech', dataset_domain: 'fintech', chapter_num: null,
    difficulty: 'medium', grading_mode: 'ordered', tags: ['join', 'order_by', 'limit'],
    description: `완료된 거래 중 balance_after 기준 가장 높은 잔액을 기록한 거래 10건의 유저 이름(name), 거래 유형(type), 금액(amount), balance_after를 조회하세요.`,
    solution_sql: `SELECT u.name, t.type, t.amount, t.balance_after FROM transactions t JOIN accounts a ON t.account_id = a.id JOIN users u ON a.user_id = u.id WHERE t.status = 'completed' ORDER BY t.balance_after DESC LIMIT 10;`,
  },
  {
    title: '가입 이후 거래 없는 유저',
    track: 'case', domain: 'fintech', dataset_domain: 'fintech', chapter_num: null,
    difficulty: 'hard', grading_mode: 'unordered', tags: ['left_join', 'null', 'join'],
    description: `계좌는 있지만 거래 내역이 하나도 없는 유저의 name, email을 조회하세요.`,
    solution_sql: `SELECT DISTINCT u.name, u.email FROM users u JOIN accounts a ON u.id = a.user_id LEFT JOIN transactions t ON a.id = t.account_id WHERE t.id IS NULL ORDER BY u.name;`,
  },

  // ── TRACK B: 물류 (20) ─────────────────────────────────────────────────────
  {
    title: '지역별 창고 수',
    track: 'case', domain: 'logistics', dataset_domain: 'logistics', chapter_num: null,
    difficulty: 'easy', grading_mode: 'unordered', tags: ['group_by', 'count'],
    description: `warehouses 테이블에서 region별 창고 수(warehouse_cnt)를 조회하세요.`,
    solution_sql: `SELECT region, COUNT(*) AS warehouse_cnt FROM warehouses GROUP BY region ORDER BY warehouse_cnt DESC;`,
  },
  {
    title: '카테고리별 평균 단위 비용',
    track: 'case', domain: 'logistics', dataset_domain: 'logistics', chapter_num: null,
    difficulty: 'easy', grading_mode: 'unordered', tags: ['group_by', 'avg'],
    description: `products 테이블에서 category별 평균 단위 비용(avg_unit_cost)을 조회하세요.\n- avg_unit_cost 내림차순 정렬`,
    solution_sql: `SELECT category, ROUND(AVG(unit_cost), 0) AS avg_unit_cost FROM products GROUP BY category ORDER BY avg_unit_cost DESC;`,
  },
  {
    title: '배송지별 배송 현황',
    track: 'case', domain: 'logistics', dataset_domain: 'logistics', chapter_num: null,
    difficulty: 'medium', grading_mode: 'unordered', tags: ['group_by', 'count', 'case'],
    description: `destination_city별 총 배송 수(shipment_cnt)와 완료된 배송 수(delivered_cnt)를 조회하세요.\n- shipment_cnt 내림차순 정렬`,
    solution_sql: `SELECT destination_city, COUNT(*) AS shipment_cnt, SUM(CASE WHEN status = 'delivered' THEN 1 ELSE 0 END) AS delivered_cnt FROM shipments GROUP BY destination_city ORDER BY shipment_cnt DESC;`,
  },
  {
    title: '재고 총 중량 계산',
    track: 'case', domain: 'logistics', dataset_domain: 'logistics', chapter_num: null,
    difficulty: 'medium', grading_mode: 'unordered', tags: ['join', 'group_by', 'sum'],
    description: `창고별 총 재고 중량(total_weight_kg)을 계산하세요.\n- total_weight_kg = SUM(i.quantity × p.weight_kg)\n- 창고명(warehouse name), total_weight_kg 출력\n- 내림차순 정렬`,
    solution_sql: `SELECT w.name, ROUND(SUM(i.quantity * p.weight_kg), 1) AS total_weight_kg FROM inventory i JOIN warehouses w ON i.warehouse_id = w.id JOIN products p ON i.product_id = p.id GROUP BY w.id, w.name ORDER BY total_weight_kg DESC;`,
  },
  {
    title: '상품 무게 구간 분류',
    track: 'case', domain: 'logistics', dataset_domain: 'logistics', chapter_num: null,
    difficulty: 'medium', grading_mode: 'ordered', tags: ['case', 'order_by'],
    description: `products 테이블에서 name, weight_kg와 함께 무게 구간(weight_class)을 분류하세요.\n- weight_kg < 0.5: '경량'\n- weight_kg < 2.0: '중량'\n- 그 외: '중량물'\n- weight_kg 오름차순 정렬`,
    solution_sql: `SELECT name, weight_kg, CASE WHEN weight_kg < 0.5 THEN '경량' WHEN weight_kg < 2.0 THEN '중량' ELSE '중량물' END AS weight_class FROM products ORDER BY weight_kg;`,
  },
  {
    title: '배송별 포함 상품 종류 및 총 수량',
    track: 'case', domain: 'logistics', dataset_domain: 'logistics', chapter_num: null,
    difficulty: 'medium', grading_mode: 'unordered', tags: ['join', 'group_by'],
    description: `배송(shipment)별 포함된 상품 종류 수(item_types)와 총 수량(total_qty)을 조회하세요.\n- 배송 id, destination_city, item_types, total_qty 출력\n- total_qty 내림차순 정렬`,
    solution_sql: `SELECT s.id, s.destination_city, COUNT(si.id) AS item_types, SUM(si.quantity) AS total_qty FROM shipments s JOIN shipment_items si ON s.id = si.shipment_id GROUP BY s.id, s.destination_city ORDER BY total_qty DESC;`,
  },
  {
    title: 'SKU별 전체 재고 현황',
    track: 'case', domain: 'logistics', dataset_domain: 'logistics', chapter_num: null,
    difficulty: 'medium', grading_mode: 'unordered', tags: ['join', 'group_by', 'sum'],
    description: `products의 sku와 name별로 모든 창고의 재고 합계(total_qty)를 조회하세요.\n- total_qty 내림차순 정렬`,
    solution_sql: `SELECT p.sku, p.name, SUM(i.quantity) AS total_qty FROM inventory i JOIN products p ON i.product_id = p.id GROUP BY p.id, p.sku, p.name ORDER BY total_qty DESC;`,
  },
  {
    title: '창고별 최대 재고 상품',
    track: 'case', domain: 'logistics', dataset_domain: 'logistics', chapter_num: null,
    difficulty: 'hard', grading_mode: 'unordered', tags: ['window', 'rank', 'join'],
    description: `창고별로 재고량(quantity)이 가장 많은 상품 1개씩을 조회하세요.\n- 창고명(warehouse name), 상품명(product name), quantity 출력`,
    solution_sql: `WITH inv_rank AS (SELECT i.warehouse_id, i.product_id, i.quantity, RANK() OVER (PARTITION BY i.warehouse_id ORDER BY i.quantity DESC) AS rnk FROM inventory i) SELECT w.name AS warehouse_name, p.name AS product_name, ir.quantity FROM inv_rank ir JOIN warehouses w ON ir.warehouse_id = w.id JOIN products p ON ir.product_id = p.id WHERE ir.rnk = 1 ORDER BY ir.quantity DESC;`,
  },
  {
    title: '카테고리별 배송 출하량',
    track: 'case', domain: 'logistics', dataset_domain: 'logistics', chapter_num: null,
    difficulty: 'medium', grading_mode: 'unordered', tags: ['join', 'group_by'],
    description: `완료된 배송(delivered)의 상품 카테고리별 총 출하 수량(total_shipped)을 조회하세요.\n- total_shipped 내림차순 정렬`,
    solution_sql: `SELECT p.category, SUM(si.quantity) AS total_shipped FROM shipment_items si JOIN products p ON si.product_id = p.id JOIN shipments s ON si.shipment_id = s.id WHERE s.status = 'delivered' GROUP BY p.category ORDER BY total_shipped DESC;`,
  },
  {
    title: '최근 지연 배송 상품',
    track: 'case', domain: 'logistics', dataset_domain: 'logistics', chapter_num: null,
    difficulty: 'medium', grading_mode: 'unordered', tags: ['join', 'where'],
    description: `status = 'delayed'인 배송에 포함된 상품의 이름(product name), 카테고리(category), 수량(quantity)을 조회하세요.`,
    solution_sql: `SELECT p.name AS product_name, p.category, si.quantity FROM shipments s JOIN shipment_items si ON s.id = si.shipment_id JOIN products p ON si.product_id = p.id WHERE s.status = 'delayed' ORDER BY si.quantity DESC;`,
  },
  {
    title: '가장 많이 배송된 목적지 TOP 5',
    track: 'case', domain: 'logistics', dataset_domain: 'logistics', chapter_num: null,
    difficulty: 'easy', grading_mode: 'ordered', tags: ['group_by', 'order_by', 'limit'],
    description: `완료된 배송(delivered) 기준 destination_city별 배송 횟수(shipment_cnt) TOP 5를 조회하세요.`,
    solution_sql: `SELECT destination_city, COUNT(*) AS shipment_cnt FROM shipments WHERE status = 'delivered' GROUP BY destination_city ORDER BY shipment_cnt DESC LIMIT 5;`,
  },
  {
    title: '창고별 출발 배송 건수',
    track: 'case', domain: 'logistics', dataset_domain: 'logistics', chapter_num: null,
    difficulty: 'medium', grading_mode: 'unordered', tags: ['join', 'group_by'],
    description: `창고별 출발 배송 건수(outbound_cnt)를 조회하세요.\n- 창고명(warehouse name), outbound_cnt 출력\n- outbound_cnt 내림차순 정렬`,
    solution_sql: `SELECT w.name, COUNT(s.id) AS outbound_cnt FROM shipments s JOIN warehouses w ON s.warehouse_id = w.id GROUP BY w.id, w.name ORDER BY outbound_cnt DESC;`,
  },
  {
    title: '수도권 vs 기타 지역 재고 비교',
    track: 'case', domain: 'logistics', dataset_domain: 'logistics', chapter_num: null,
    difficulty: 'hard', grading_mode: 'unordered', tags: ['case', 'join', 'group_by'],
    description: `창고 region을 '수도권'과 '기타'로 구분하여 각 그룹의 총 재고 수량(total_qty)과 총 재고 가치(total_value)를 조회하세요.`,
    solution_sql: `SELECT CASE WHEN w.region = '수도권' THEN '수도권' ELSE '기타' END AS region_group, SUM(i.quantity) AS total_qty, SUM(i.quantity * p.unit_cost) AS total_value FROM inventory i JOIN warehouses w ON i.warehouse_id = w.id JOIN products p ON i.product_id = p.id GROUP BY region_group ORDER BY total_value DESC;`,
  },
  {
    title: '창고별 취급 상품 종류 수',
    track: 'case', domain: 'logistics', dataset_domain: 'logistics', chapter_num: null,
    difficulty: 'medium', grading_mode: 'unordered', tags: ['join', 'group_by', 'count'],
    description: `재고가 있는(quantity > 0) 창고별 취급 상품 종류 수(sku_cnt)를 조회하세요.\n- 창고명(warehouse name), sku_cnt 출력\n- sku_cnt 내림차순 정렬`,
    solution_sql: `SELECT w.name, COUNT(DISTINCT i.product_id) AS sku_cnt FROM inventory i JOIN warehouses w ON i.warehouse_id = w.id WHERE i.quantity > 0 GROUP BY w.id, w.name ORDER BY sku_cnt DESC;`,
  },
  {
    title: '배송된 적 없는 상품',
    track: 'case', domain: 'logistics', dataset_domain: 'logistics', chapter_num: null,
    difficulty: 'medium', grading_mode: 'unordered', tags: ['left_join', 'null'],
    description: `shipment_items에 한 번도 포함되지 않은 상품의 name과 category를 조회하세요.`,
    solution_sql: `SELECT p.name, p.category FROM products p LEFT JOIN shipment_items si ON p.id = si.product_id WHERE si.id IS NULL ORDER BY p.name;`,
  },
  {
    title: '배송 무게 기준 배송 TOP 5',
    track: 'case', domain: 'logistics', dataset_domain: 'logistics', chapter_num: null,
    difficulty: 'hard', grading_mode: 'ordered', tags: ['join', 'group_by', 'order_by'],
    description: `배송별 총 중량(total_weight_kg)을 계산하여 TOP 5의 배송 id, destination_city, total_weight_kg를 조회하세요.`,
    solution_sql: `SELECT s.id, s.destination_city, ROUND(SUM(si.quantity * p.weight_kg), 1) AS total_weight_kg FROM shipments s JOIN shipment_items si ON s.id = si.shipment_id JOIN products p ON si.product_id = p.id GROUP BY s.id, s.destination_city ORDER BY total_weight_kg DESC LIMIT 5;`,
  },
  {
    title: '재고 부족 우선순위(부족도 기준)',
    track: 'case', domain: 'logistics', dataset_domain: 'logistics', chapter_num: null,
    difficulty: 'medium', grading_mode: 'ordered', tags: ['join', 'where', 'arithmetic'],
    description: `quantity < reorder_point인 재고의 부족도(shortage = reorder_point - quantity)를 계산하여 창고명(warehouse name), 상품명(product name), quantity, reorder_point, shortage를 조회하세요.\n- shortage 내림차순 정렬`,
    solution_sql: `SELECT w.name AS warehouse_name, p.name AS product_name, i.quantity, i.reorder_point, i.reorder_point - i.quantity AS shortage FROM inventory i JOIN warehouses w ON i.warehouse_id = w.id JOIN products p ON i.product_id = p.id WHERE i.quantity < i.reorder_point ORDER BY shortage DESC;`,
  },
  {
    title: '하루 여러 건 배송 출발한 날',
    track: 'case', domain: 'logistics', dataset_domain: 'logistics', chapter_num: null,
    difficulty: 'medium', grading_mode: 'ordered', tags: ['group_by', 'having', 'date'],
    description: `같은 날 2건 이상 배송이 출발한 날짜(date)와 배송 건수(shipment_cnt)를 조회하세요.\n- shipment_cnt 내림차순 정렬`,
    solution_sql: `SELECT DATE(shipped_at) AS date, COUNT(*) AS shipment_cnt FROM shipments GROUP BY date HAVING COUNT(*) > 1 ORDER BY shipment_cnt DESC;`,
  },
  {
    title: '배송사별 총 출하 수량',
    track: 'case', domain: 'logistics', dataset_domain: 'logistics', chapter_num: null,
    difficulty: 'medium', grading_mode: 'unordered', tags: ['join', 'group_by', 'sum'],
    description: `완료된 배송(delivered) 기준으로 배송사(carrier)별 총 출하 수량(total_qty)을 조회하세요.\n- total_qty 내림차순 정렬`,
    solution_sql: `SELECT s.carrier, SUM(si.quantity) AS total_qty FROM shipments s JOIN shipment_items si ON s.id = si.shipment_id WHERE s.status = 'delivered' GROUP BY s.carrier ORDER BY total_qty DESC;`,
  },
  {
    title: '재고 보충 필요 창고 요약',
    track: 'case', domain: 'logistics', dataset_domain: 'logistics', chapter_num: null,
    difficulty: 'medium', grading_mode: 'unordered', tags: ['join', 'group_by', 'where'],
    description: `quantity < reorder_point인 창고별 보충 필요 품목 수(shortage_items)를 조회하세요.\n- 창고명(warehouse name), shortage_items 출력\n- shortage_items 내림차순 정렬`,
    solution_sql: `SELECT w.name, COUNT(*) AS shortage_items FROM inventory i JOIN warehouses w ON i.warehouse_id = w.id WHERE i.quantity < i.reorder_point GROUP BY w.id, w.name ORDER BY shortage_items DESC;`,
  },

  // ── TRACK B: 미디어 (20) ────────────────────────────────────────────────────
  {
    title: '국가별 크리에이터 수',
    track: 'case', domain: 'media', dataset_domain: 'media', chapter_num: null,
    difficulty: 'easy', grading_mode: 'unordered', tags: ['group_by', 'count'],
    description: `creators 테이블에서 country별 크리에이터 수(creator_cnt)를 조회하세요.\n- creator_cnt 내림차순 정렬`,
    solution_sql: `SELECT country, COUNT(*) AS creator_cnt FROM creators GROUP BY country ORDER BY creator_cnt DESC;`,
  },
  {
    title: '카테고리별 영상 수 및 총 조회수',
    track: 'case', domain: 'media', dataset_domain: 'media', chapter_num: null,
    difficulty: 'easy', grading_mode: 'unordered', tags: ['group_by', 'count', 'sum'],
    description: `published 상태 영상의 category별 영상 수(video_cnt)와 총 조회수(total_views)를 조회하세요.\n- total_views 내림차순 정렬`,
    solution_sql: `SELECT category, COUNT(*) AS video_cnt, SUM(view_cnt) AS total_views FROM videos WHERE status = 'published' GROUP BY category ORDER BY total_views DESC;`,
  },
  {
    title: '좋아요 많은 영상 TOP 5',
    track: 'case', domain: 'media', dataset_domain: 'media', chapter_num: null,
    difficulty: 'easy', grading_mode: 'ordered', tags: ['order_by', 'limit'],
    description: `published 상태 영상 중 like_cnt 기준 TOP 5의 title, like_cnt, view_cnt를 조회하세요.`,
    solution_sql: `SELECT title, like_cnt, view_cnt FROM videos WHERE status = 'published' ORDER BY like_cnt DESC LIMIT 5;`,
  },
  {
    title: '좋아요 대비 조회수 비율',
    track: 'case', domain: 'media', dataset_domain: 'media', chapter_num: null,
    difficulty: 'medium', grading_mode: 'unordered', tags: ['arithmetic', 'where'],
    description: `published 상태 영상의 title, view_cnt, like_cnt와 함께 좋아요율(like_rate_pct = ROUND(like_cnt * 100.0 / NULLIF(view_cnt, 0), 2))을 조회하세요.\n- view_cnt > 0인 영상만\n- like_rate_pct 내림차순 정렬`,
    solution_sql: `SELECT title, view_cnt, like_cnt, ROUND(like_cnt * 100.0 / NULLIF(view_cnt, 0), 2) AS like_rate_pct FROM videos WHERE status = 'published' AND view_cnt > 0 ORDER BY like_rate_pct DESC;`,
  },
  {
    title: '뷰어별 총 시청 시간 TOP 10',
    track: 'case', domain: 'media', dataset_domain: 'media', chapter_num: null,
    difficulty: 'medium', grading_mode: 'ordered', tags: ['join', 'group_by', 'sum'],
    description: `뷰어별 총 시청 시간을 시간(hours) 단위로 계산하여 TOP 10의 nickname과 total_watch_hours를 조회하세요.\n- total_watch_hours = ROUND(SUM(watch_duration_sec) / 3600.0, 1)`,
    solution_sql: `SELECT va.nickname, ROUND(SUM(v.watch_duration_sec) / 3600.0, 1) AS total_watch_hours FROM views v JOIN viewer_accounts va ON v.viewer_id = va.id GROUP BY va.id, va.nickname ORDER BY total_watch_hours DESC LIMIT 10;`,
  },
  {
    title: '크리에이터 카테고리별 평균 구독자',
    track: 'case', domain: 'media', dataset_domain: 'media', chapter_num: null,
    difficulty: 'easy', grading_mode: 'unordered', tags: ['group_by', 'avg'],
    description: `creators 테이블에서 category별 평균 구독자 수(avg_subs)를 조회하세요.\n- avg_subs 내림차순 정렬`,
    solution_sql: `SELECT category, ROUND(AVG(subscriber_cnt), 0) AS avg_subs FROM creators GROUP BY category ORDER BY avg_subs DESC;`,
  },
  {
    title: '드래프트(미발행) 영상 현황',
    track: 'case', domain: 'media', dataset_domain: 'media', chapter_num: null,
    difficulty: 'medium', grading_mode: 'unordered', tags: ['join', 'group_by', 'where'],
    description: `status = 'draft'인 영상을 크리에이터별로 집계하여 이름(name)과 draft_cnt를 조회하세요.\n- draft_cnt 내림차순 정렬`,
    solution_sql: `SELECT c.name, COUNT(v.id) AS draft_cnt FROM videos v JOIN creators c ON v.creator_id = c.id WHERE v.status = 'draft' GROUP BY c.id, c.name ORDER BY draft_cnt DESC;`,
  },
  {
    title: '가장 긴 영상 TOP 5',
    track: 'case', domain: 'media', dataset_domain: 'media', chapter_num: null,
    difficulty: 'easy', grading_mode: 'ordered', tags: ['join', 'order_by', 'limit'],
    description: `published 상태 영상 중 길이 기준 TOP 5의 title, 크리에이터 이름(creator name), duration_min(ROUND(duration_sec / 60.0, 1))을 조회하세요.`,
    solution_sql: `SELECT v.title, c.name AS creator_name, ROUND(v.duration_sec / 60.0, 1) AS duration_min FROM videos v JOIN creators c ON v.creator_id = c.id WHERE v.status = 'published' ORDER BY v.duration_sec DESC LIMIT 5;`,
  },
  {
    title: '뷰어 국가별 분포',
    track: 'case', domain: 'media', dataset_domain: 'media', chapter_num: null,
    difficulty: 'easy', grading_mode: 'unordered', tags: ['group_by', 'count'],
    description: `viewer_accounts 테이블에서 country별 뷰어 수(viewer_cnt)를 조회하세요.\n- viewer_cnt 내림차순 정렬`,
    solution_sql: `SELECT country, COUNT(*) AS viewer_cnt FROM viewer_accounts GROUP BY country ORDER BY viewer_cnt DESC;`,
  },
  {
    title: '실제 구독자 수 TOP 3 크리에이터',
    track: 'case', domain: 'media', dataset_domain: 'media', chapter_num: null,
    difficulty: 'medium', grading_mode: 'ordered', tags: ['join', 'group_by', 'order_by'],
    description: `creator_subscriptions를 집계하여 실제 구독자 수(actual_subscribers) 기준 TOP 3 크리에이터의 name과 actual_subscribers를 조회하세요.`,
    solution_sql: `SELECT c.name, COUNT(cs.viewer_id) AS actual_subscribers FROM creators c JOIN creator_subscriptions cs ON c.id = cs.creator_id GROUP BY c.id, c.name ORDER BY actual_subscribers DESC LIMIT 3;`,
  },
  {
    title: '크리에이터별 평균 영상 길이',
    track: 'case', domain: 'media', dataset_domain: 'media', chapter_num: null,
    difficulty: 'medium', grading_mode: 'unordered', tags: ['join', 'group_by', 'avg'],
    description: `크리에이터별 평균 영상 길이(avg_duration_min)를 분 단위로 조회하세요.\n- avg_duration_min = ROUND(AVG(duration_sec) / 60.0, 1)\n- avg_duration_min 내림차순 정렬`,
    solution_sql: `SELECT c.name, ROUND(AVG(v.duration_sec) / 60.0, 1) AS avg_duration_min FROM creators c JOIN videos v ON c.id = v.creator_id GROUP BY c.id, c.name ORDER BY avg_duration_min DESC;`,
  },
  {
    title: '시청 기록 없는 영상',
    track: 'case', domain: 'media', dataset_domain: 'media', chapter_num: null,
    difficulty: 'medium', grading_mode: 'unordered', tags: ['left_join', 'null'],
    description: `views 기록이 없는 published 상태 영상의 title과 published_at을 조회하세요.`,
    solution_sql: `SELECT v.title, v.published_at FROM videos v LEFT JOIN views vw ON v.id = vw.video_id WHERE vw.id IS NULL AND v.status = 'published' ORDER BY v.published_at DESC;`,
  },
  {
    title: '크리에이터별 총 댓글 좋아요',
    track: 'case', domain: 'media', dataset_domain: 'media', chapter_num: null,
    difficulty: 'medium', grading_mode: 'unordered', tags: ['join', 'group_by', 'sum'],
    description: `크리에이터별로 자신의 영상에 달린 댓글의 좋아요 합계(total_comment_likes)를 조회하세요.\n- 크리에이터 이름(name), total_comment_likes 출력\n- 내림차순 정렬`,
    solution_sql: `SELECT c.name, SUM(com.like_cnt) AS total_comment_likes FROM comments com JOIN videos v ON com.video_id = v.id JOIN creators c ON v.creator_id = c.id GROUP BY c.id, c.name ORDER BY total_comment_likes DESC;`,
  },
  {
    title: '월별 영상 발행 수',
    track: 'case', domain: 'media', dataset_domain: 'media', chapter_num: null,
    difficulty: 'medium', grading_mode: 'ordered', tags: ['group_by', 'date'],
    description: `published 상태 영상을 연도-월별로 집계하여 발행 수(video_cnt)를 조회하세요.\n- 최신 월 순 정렬`,
    solution_sql: `SELECT STRFTIME('%Y-%m', published_at) AS month, COUNT(*) AS video_cnt FROM videos WHERE status = 'published' AND published_at IS NOT NULL GROUP BY month ORDER BY month DESC;`,
  },
  {
    title: '영상 길이 구간별 평균 조회수',
    track: 'case', domain: 'media', dataset_domain: 'media', chapter_num: null,
    difficulty: 'medium', grading_mode: 'unordered', tags: ['case', 'group_by', 'avg'],
    description: `published 영상을 길이 구간으로 분류하여 구간별 영상 수(video_cnt)와 평균 조회수(avg_views)를 조회하세요.\n- 5분 미만 / 5~15분 / 15~30분 / 30분 이상`,
    solution_sql: `SELECT CASE WHEN duration_sec < 300 THEN '5분 미만' WHEN duration_sec < 900 THEN '5~15분' WHEN duration_sec < 1800 THEN '15~30분' ELSE '30분 이상' END AS duration_group, COUNT(*) AS video_cnt, ROUND(AVG(view_cnt), 0) AS avg_views FROM videos WHERE status = 'published' GROUP BY duration_group ORDER BY avg_views DESC;`,
  },
  {
    title: '댓글 평균 좋아요 높은 영상',
    track: 'case', domain: 'media', dataset_domain: 'media', chapter_num: null,
    difficulty: 'medium', grading_mode: 'unordered', tags: ['join', 'group_by', 'avg'],
    description: `영상별 댓글 평균 좋아요(avg_comment_likes)를 계산하여 title, avg_comment_likes를 조회하세요.\n- avg_comment_likes 내림차순 정렬`,
    solution_sql: `SELECT v.title, ROUND(AVG(c.like_cnt), 1) AS avg_comment_likes FROM comments c JOIN videos v ON c.video_id = v.id GROUP BY v.id, v.title ORDER BY avg_comment_likes DESC;`,
  },
  {
    title: '기기별 시청 분포',
    track: 'case', domain: 'media', dataset_domain: 'media', chapter_num: null,
    difficulty: 'medium', grading_mode: 'unordered', tags: ['group_by', 'arithmetic'],
    description: `views 테이블에서 device별 시청 건수(view_cnt)와 전체 대비 비율(rate_pct)을 조회하세요.\n- rate_pct = ROUND(view_cnt * 100.0 / total, 1)`,
    solution_sql: `SELECT device, COUNT(*) AS view_cnt, ROUND(COUNT(*) * 100.0 / (SELECT COUNT(*) FROM views), 1) AS rate_pct FROM views GROUP BY device ORDER BY view_cnt DESC;`,
  },
  {
    title: '상위 댓글 좋아요 TOP 10',
    track: 'case', domain: 'media', dataset_domain: 'media', chapter_num: null,
    difficulty: 'medium', grading_mode: 'ordered', tags: ['join', 'order_by', 'limit'],
    description: `댓글 좋아요(like_cnt) 기준 TOP 10의 영상 제목(video_title), 댓글 내용(content), like_cnt를 조회하세요.`,
    solution_sql: `SELECT v.title AS video_title, c.content, c.like_cnt FROM comments c JOIN videos v ON c.video_id = v.id ORDER BY c.like_cnt DESC LIMIT 10;`,
  },
  {
    title: '구독자 수 vs 실제 구독 수 차이',
    track: 'case', domain: 'media', dataset_domain: 'media', chapter_num: null,
    difficulty: 'hard', grading_mode: 'unordered', tags: ['join', 'group_by', 'arithmetic'],
    description: `크리에이터별로 선언된 구독자 수(subscriber_cnt)와 creator_subscriptions 실제 구독 수(actual_subs)의 차이(gap)를 조회하세요.\n- name, subscriber_cnt, actual_subs, gap 출력\n- gap 내림차순 정렬`,
    solution_sql: `SELECT c.name, c.subscriber_cnt, COUNT(cs.viewer_id) AS actual_subs, c.subscriber_cnt - COUNT(cs.viewer_id) AS gap FROM creators c LEFT JOIN creator_subscriptions cs ON c.id = cs.creator_id GROUP BY c.id, c.name, c.subscriber_cnt ORDER BY gap DESC;`,
  },
  {
    title: '신규 크리에이터 현황',
    track: 'case', domain: 'media', dataset_domain: 'media', chapter_num: null,
    difficulty: 'easy', grading_mode: 'ordered', tags: ['where', 'order_by'],
    description: `2023년 이후 가입한(joined_at >= '2023-01-01') 크리에이터의 name, channel, category, joined_at을 조회하세요.\n- joined_at 오름차순 정렬`,
    solution_sql: `SELECT name, channel, category, joined_at FROM creators WHERE joined_at >= '2023-01-01' ORDER BY joined_at;`,
  },

  // ── TRACK B: HR (20) ────────────────────────────────────────────────────────
  {
    title: '부서별 예산 대비 인건비 비율',
    track: 'case', domain: 'hr', dataset_domain: 'hr', chapter_num: null,
    difficulty: 'hard', grading_mode: 'unordered', tags: ['join', 'group_by', 'arithmetic'],
    description: `부서별 총 연봉(total_salary)과 예산(budget) 대비 비율(salary_to_budget_pct)을 조회하세요.\n- salary_to_budget_pct = ROUND(total_salary * 100.0 / budget, 1)\n- active 직원만\n- 내림차순 정렬`,
    solution_sql: `SELECT d.name, d.budget, SUM(e.salary) AS total_salary, ROUND(SUM(e.salary) * 100.0 / d.budget, 1) AS salary_to_budget_pct FROM employees e JOIN departments d ON e.department_id = d.id WHERE e.status = 'active' GROUP BY d.id, d.name, d.budget ORDER BY salary_to_budget_pct DESC;`,
  },
  {
    title: '직급(position)별 인원 수',
    track: 'case', domain: 'hr', dataset_domain: 'hr', chapter_num: null,
    difficulty: 'easy', grading_mode: 'unordered', tags: ['group_by', 'count'],
    description: `active 직원의 position별 인원 수(cnt)를 조회하세요.\n- cnt 내림차순 정렬`,
    solution_sql: `SELECT position, COUNT(*) AS cnt FROM employees WHERE status = 'active' GROUP BY position ORDER BY cnt DESC;`,
  },
  {
    title: '재택근무 비율',
    track: 'case', domain: 'hr', dataset_domain: 'hr', chapter_num: null,
    difficulty: 'medium', grading_mode: 'unordered', tags: ['case', 'arithmetic'],
    description: `2024-03-18 출근 기록에서 재택(remote) 근무 비율(remote_pct)을 조회하세요.\n- remote_pct = ROUND(remote_cnt * 100.0 / total_cnt, 1)`,
    solution_sql: `SELECT COUNT(*) AS total_cnt, SUM(CASE WHEN work_type = 'remote' THEN 1 ELSE 0 END) AS remote_cnt, ROUND(SUM(CASE WHEN work_type = 'remote' THEN 1 ELSE 0 END) * 100.0 / COUNT(*), 1) AS remote_pct FROM attendance WHERE work_date = '2024-03-18';`,
  },
  {
    title: '직원별 성과 평균 점수',
    track: 'case', domain: 'hr', dataset_domain: 'hr', chapter_num: null,
    difficulty: 'medium', grading_mode: 'unordered', tags: ['join', 'group_by', 'avg'],
    description: `직원별 평균 성과 점수(avg_score)를 조회하세요.\n- 이름(name), 부서명(department name), avg_score 출력\n- avg_score 내림차순 정렬`,
    solution_sql: `SELECT e.name, d.name AS department, ROUND(AVG(pr.score), 1) AS avg_score FROM performance_reviews pr JOIN employees e ON pr.employee_id = e.id JOIN departments d ON e.department_id = d.id GROUP BY e.id, e.name, d.name ORDER BY avg_score DESC;`,
  },
  {
    title: '레벨별 연봉 분포',
    track: 'case', domain: 'hr', dataset_domain: 'hr', chapter_num: null,
    difficulty: 'medium', grading_mode: 'unordered', tags: ['group_by', 'avg', 'min', 'max'],
    description: `active 직원의 level별 평균(avg_salary), 최저(min_salary), 최고(max_salary) 연봉과 인원 수(cnt)를 조회하세요.\n- avg_salary 내림차순 정렬`,
    solution_sql: `SELECT level, COUNT(*) AS cnt, ROUND(AVG(salary), 0) AS avg_salary, MIN(salary) AS min_salary, MAX(salary) AS max_salary FROM employees WHERE status = 'active' GROUP BY level ORDER BY avg_salary DESC;`,
  },
  {
    title: '부서별 직원 수 vs 등록 인원',
    track: 'case', domain: 'hr', dataset_domain: 'hr', chapter_num: null,
    difficulty: 'medium', grading_mode: 'unordered', tags: ['join', 'group_by'],
    description: `부서별 등록 인원(head_count)과 실제 active 직원 수(actual_cnt)를 비교 조회하세요.`,
    solution_sql: `SELECT d.name, d.head_count AS registered, COUNT(e.id) AS actual_cnt FROM departments d LEFT JOIN employees e ON d.id = e.department_id AND e.status = 'active' GROUP BY d.id, d.name, d.head_count ORDER BY d.head_count DESC;`,
  },
  {
    title: '병가 사용자 목록',
    track: 'case', domain: 'hr', dataset_domain: 'hr', chapter_num: null,
    difficulty: 'medium', grading_mode: 'unordered', tags: ['join', 'where', 'group_by'],
    description: `type = '병가', status = 'approved'인 휴가를 직원별로 집계하여 이름(name), 부서(department name), 총 병가 일수(sick_days)를 조회하세요.`,
    solution_sql: `SELECT e.name, d.name AS department, SUM(l.days) AS sick_days FROM leaves l JOIN employees e ON l.employee_id = e.id JOIN departments d ON e.department_id = d.id WHERE l.type = '병가' AND l.status = 'approved' GROUP BY e.id, e.name, d.name ORDER BY sick_days DESC;`,
  },
  {
    title: '체크아웃 없는 근무 기록',
    track: 'case', domain: 'hr', dataset_domain: 'hr', chapter_num: null,
    difficulty: 'medium', grading_mode: 'unordered', tags: ['join', 'where', 'null'],
    description: `check_out이 NULL이고 status가 'absent'가 아닌 근무 기록의 직원 이름(name)과 근무일(work_date), check_in을 조회하세요.`,
    solution_sql: `SELECT e.name, a.work_date, a.check_in FROM attendance a JOIN employees e ON a.employee_id = e.id WHERE a.check_out IS NULL AND a.status != 'absent' ORDER BY a.work_date;`,
  },
  {
    title: '3년 이상 근속 직원',
    track: 'case', domain: 'hr', dataset_domain: 'hr', chapter_num: null,
    difficulty: 'medium', grading_mode: 'ordered', tags: ['where', 'date', 'arithmetic'],
    description: `2024-03-20 기준 근속 기간이 3년 이상인 active 직원의 name, position, hired_at을 조회하세요.\n- hired_at 오름차순 정렬`,
    solution_sql: `SELECT name, position, hired_at FROM employees WHERE JULIANDAY('2024-03-20') - JULIANDAY(hired_at) >= 3 * 365 AND status = 'active' ORDER BY hired_at;`,
  },
  {
    title: '연봉 통계 (최고/최저/평균)',
    track: 'case', domain: 'hr', dataset_domain: 'hr', chapter_num: null,
    difficulty: 'easy', grading_mode: 'unordered', tags: ['max', 'min', 'avg'],
    description: `active 직원의 최고 연봉(max_salary), 최저 연봉(min_salary), 평균 연봉(avg_salary)을 한 행으로 조회하세요.`,
    solution_sql: `SELECT MAX(salary) AS max_salary, MIN(salary) AS min_salary, ROUND(AVG(salary), 0) AS avg_salary FROM employees WHERE status = 'active';`,
  },
  {
    title: '부서별 2023H2 성과 평균 점수',
    track: 'case', domain: 'hr', dataset_domain: 'hr', chapter_num: null,
    difficulty: 'medium', grading_mode: 'unordered', tags: ['join', 'group_by', 'avg'],
    description: `2023H2 성과 리뷰 기준 부서별 평균 점수(avg_score)를 조회하세요.\n- 부서명(name), avg_score 출력\n- avg_score 내림차순 정렬`,
    solution_sql: `SELECT d.name, ROUND(AVG(pr.score), 1) AS avg_score FROM performance_reviews pr JOIN employees e ON pr.employee_id = e.id JOIN departments d ON e.department_id = d.id WHERE pr.period = '2023H2' GROUP BY d.id, d.name ORDER BY avg_score DESC;`,
  },
  {
    title: '대기 중인 휴가 신청',
    track: 'case', domain: 'hr', dataset_domain: 'hr', chapter_num: null,
    difficulty: 'easy', grading_mode: 'ordered', tags: ['join', 'where'],
    description: `status = 'pending'인 휴가 신청의 직원 이름(name), 휴가 유형(type), 시작일(start_date), 종료일(end_date), 일수(days)를 조회하세요.\n- start_date 오름차순 정렬`,
    solution_sql: `SELECT e.name, l.type, l.start_date, l.end_date, l.days FROM leaves l JOIN employees e ON l.employee_id = e.id WHERE l.status = 'pending' ORDER BY l.start_date;`,
  },
  {
    title: '출장 현황 요약',
    track: 'case', domain: 'hr', dataset_domain: 'hr', chapter_num: null,
    difficulty: 'medium', grading_mode: 'ordered', tags: ['join', 'where'],
    description: `type = '출장', status = 'approved'인 휴가의 직원 이름(name), 부서(department name), 출장 기간(start_date ~ end_date)을 조회하세요.\n- start_date 오름차순 정렬`,
    solution_sql: `SELECT e.name, d.name AS department, l.start_date, l.end_date FROM leaves l JOIN employees e ON l.employee_id = e.id JOIN departments d ON e.department_id = d.id WHERE l.type = '출장' AND l.status = 'approved' ORDER BY l.start_date;`,
  },
  {
    title: '성과 리뷰 없는 직원',
    track: 'case', domain: 'hr', dataset_domain: 'hr', chapter_num: null,
    difficulty: 'medium', grading_mode: 'unordered', tags: ['left_join', 'null'],
    description: `performance_reviews에 등록되지 않은 active 직원의 name, position, 부서명(department name)을 조회하세요.`,
    solution_sql: `SELECT e.name, e.position, d.name AS department FROM employees e JOIN departments d ON e.department_id = d.id LEFT JOIN performance_reviews pr ON e.id = pr.employee_id WHERE pr.id IS NULL AND e.status = 'active' ORDER BY e.name;`,
  },
  {
    title: '매니저 없는 직원(팀장급)',
    track: 'case', domain: 'hr', dataset_domain: 'hr', chapter_num: null,
    difficulty: 'easy', grading_mode: 'ordered', tags: ['where', 'null'],
    description: `manager_id가 NULL인 active 직원의 name, position, salary를 조회하세요.\n- salary 내림차순 정렬`,
    solution_sql: `SELECT name, position, salary FROM employees WHERE manager_id IS NULL AND status = 'active' ORDER BY salary DESC;`,
  },
  {
    title: '매니저별 직속 팀원 수',
    track: 'case', domain: 'hr', dataset_domain: 'hr', chapter_num: null,
    difficulty: 'medium', grading_mode: 'unordered', tags: ['join', 'group_by'],
    description: `각 매니저의 이름(manager_name)과 직속 팀원 수(direct_reports)를 조회하세요.\n- active 직원 기준\n- direct_reports 내림차순 정렬`,
    solution_sql: `SELECT m.name AS manager_name, COUNT(e.id) AS direct_reports FROM employees e JOIN employees m ON e.manager_id = m.id WHERE e.status = 'active' GROUP BY m.id, m.name ORDER BY direct_reports DESC;`,
  },
  {
    title: '부서별 총 휴가 사용 일수',
    track: 'case', domain: 'hr', dataset_domain: 'hr', chapter_num: null,
    difficulty: 'medium', grading_mode: 'unordered', tags: ['join', 'group_by', 'sum'],
    description: `부서별 승인된(status='approved') 휴가 총 사용 일수(total_leave_days)를 조회하세요.\n- 부서명(name), total_leave_days 출력\n- total_leave_days 내림차순 정렬`,
    solution_sql: `SELECT d.name, SUM(l.days) AS total_leave_days FROM leaves l JOIN employees e ON l.employee_id = e.id JOIN departments d ON e.department_id = d.id WHERE l.status = 'approved' GROUP BY d.id, d.name ORDER BY total_leave_days DESC;`,
  },
  {
    title: '성과 낮은 직원 (1~2점)',
    track: 'case', domain: 'hr', dataset_domain: 'hr', chapter_num: null,
    difficulty: 'easy', grading_mode: 'unordered', tags: ['join', 'where'],
    description: `성과 리뷰 점수가 2점 이하인 직원의 이름(name), 기간(period), 점수(score), 등급(grade), 코멘트(comments)를 조회하세요.`,
    solution_sql: `SELECT e.name, pr.period, pr.score, pr.grade, pr.comments FROM performance_reviews pr JOIN employees e ON pr.employee_id = e.id WHERE pr.score <= 2 ORDER BY pr.score, e.name;`,
  },
  {
    title: 'H1과 H2 성과 점수 비교',
    track: 'case', domain: 'hr', dataset_domain: 'hr', chapter_num: null,
    difficulty: 'hard', grading_mode: 'unordered', tags: ['case', 'group_by', 'join'],
    description: `직원별로 2023H1 점수(h1_score)와 2023H2 점수(h2_score)를 함께 조회하세요.\n- 두 기간 모두 리뷰가 있는 직원만\n- h2_score 내림차순 정렬`,
    solution_sql: `SELECT e.name, MAX(CASE WHEN pr.period = '2023H1' THEN pr.score END) AS h1_score, MAX(CASE WHEN pr.period = '2023H2' THEN pr.score END) AS h2_score FROM performance_reviews pr JOIN employees e ON pr.employee_id = e.id GROUP BY e.id, e.name HAVING h1_score IS NOT NULL AND h2_score IS NOT NULL ORDER BY h2_score DESC;`,
  },
  {
    title: '근속 연수별 평균 연봉 분석',
    track: 'case', domain: 'hr', dataset_domain: 'hr', chapter_num: null,
    difficulty: 'hard', grading_mode: 'unordered', tags: ['case', 'group_by', 'arithmetic'],
    description: `active 직원의 근속 연수를 '1년 미만', '1~3년', '3~5년', '5년 이상'으로 구분하여 구간별 평균 연봉(avg_salary)과 인원 수(cnt)를 조회하세요.\n- reference date: '2024-03-20'`,
    solution_sql: `SELECT CASE WHEN JULIANDAY('2024-03-20') - JULIANDAY(hired_at) < 365 THEN '1년 미만' WHEN JULIANDAY('2024-03-20') - JULIANDAY(hired_at) < 3 * 365 THEN '1~3년' WHEN JULIANDAY('2024-03-20') - JULIANDAY(hired_at) < 5 * 365 THEN '3~5년' ELSE '5년 이상' END AS tenure_group, COUNT(*) AS cnt, ROUND(AVG(salary), 0) AS avg_salary FROM employees WHERE status = 'active' GROUP BY tenure_group ORDER BY avg_salary DESC;`,
  },

  // ── TRACK B: 커뮤니티 (20) ─────────────────────────────────────────────────
  {
    title: '카테고리별 게시글 수 및 평균 조회수',
    track: 'case', domain: 'community', dataset_domain: 'community', chapter_num: null,
    difficulty: 'easy', grading_mode: 'unordered', tags: ['group_by', 'count', 'avg'],
    description: `posts 테이블에서 category별 게시글 수(post_cnt)와 평균 조회수(avg_views)를 조회하세요.\n- post_cnt 내림차순 정렬`,
    solution_sql: `SELECT category, COUNT(*) AS post_cnt, ROUND(AVG(view_cnt), 0) AS avg_views FROM posts GROUP BY category ORDER BY post_cnt DESC;`,
  },
  {
    title: '고평판 유저(500점 이상) 목록',
    track: 'case', domain: 'community', dataset_domain: 'community', chapter_num: null,
    difficulty: 'easy', grading_mode: 'ordered', tags: ['where', 'order_by'],
    description: `reputation이 500 이상인 유저의 username, reputation, role을 조회하세요.\n- reputation 내림차순 정렬`,
    solution_sql: `SELECT username, reputation, role FROM users WHERE reputation >= 500 ORDER BY reputation DESC;`,
  },
  {
    title: '가장 많이 채택된 댓글 작성자 TOP 5',
    track: 'case', domain: 'community', dataset_domain: 'community', chapter_num: null,
    difficulty: 'medium', grading_mode: 'ordered', tags: ['join', 'group_by', 'order_by'],
    description: `is_accepted = 1인 댓글을 작성자별로 집계하여 채택 횟수(accepted_cnt) TOP 5의 username과 accepted_cnt를 조회하세요.`,
    solution_sql: `SELECT u.username, COUNT(*) AS accepted_cnt FROM comments c JOIN users u ON c.user_id = u.id WHERE c.is_accepted = 1 GROUP BY u.id, u.username ORDER BY accepted_cnt DESC LIMIT 5;`,
  },
  {
    title: '핀 고정된 게시글',
    track: 'case', domain: 'community', dataset_domain: 'community', chapter_num: null,
    difficulty: 'easy', grading_mode: 'ordered', tags: ['join', 'where'],
    description: `is_pinned = 1인 게시글의 title, category, 작성자(username), view_cnt, upvote_cnt를 조회하세요.\n- view_cnt 내림차순 정렬`,
    solution_sql: `SELECT p.title, p.category, u.username, p.view_cnt, p.upvote_cnt FROM posts p JOIN users u ON p.user_id = u.id WHERE p.is_pinned = 1 ORDER BY p.view_cnt DESC;`,
  },
  {
    title: '태그 없는 게시글',
    track: 'case', domain: 'community', dataset_domain: 'community', chapter_num: null,
    difficulty: 'medium', grading_mode: 'unordered', tags: ['left_join', 'null'],
    description: `post_tags에 등록되지 않은 게시글의 title, category, 작성자(username)를 조회하세요.`,
    solution_sql: `SELECT p.title, p.category, u.username FROM posts p JOIN users u ON p.user_id = u.id LEFT JOIN post_tags pt ON p.id = pt.post_id WHERE pt.post_id IS NULL ORDER BY p.created_at DESC;`,
  },
  {
    title: '유저별 평균 댓글 업보트',
    track: 'case', domain: 'community', dataset_domain: 'community', chapter_num: null,
    difficulty: 'medium', grading_mode: 'unordered', tags: ['join', 'group_by', 'avg'],
    description: `댓글 작성자별 평균 댓글 업보트(avg_comment_upvotes)를 조회하세요.\n- username, avg_comment_upvotes 출력\n- avg_comment_upvotes 내림차순 정렬`,
    solution_sql: `SELECT u.username, ROUND(AVG(c.upvote_cnt), 1) AS avg_comment_upvotes FROM comments c JOIN users u ON c.user_id = u.id GROUP BY u.id, u.username ORDER BY avg_comment_upvotes DESC;`,
  },
  {
    title: '게시글 업보트 vs 댓글 수 관계',
    track: 'case', domain: 'community', dataset_domain: 'community', chapter_num: null,
    difficulty: 'medium', grading_mode: 'ordered', tags: ['arithmetic', 'order_by'],
    description: `업보트가 10 이상인 게시글의 title, upvote_cnt, comment_cnt와 함께 업보트당 댓글 비율(vote_per_comment = ROUND(CAST(upvote_cnt AS REAL) / NULLIF(comment_cnt, 0), 1))을 조회하세요.\n- upvote_cnt 내림차순 정렬`,
    solution_sql: `SELECT title, upvote_cnt, comment_cnt, ROUND(CAST(upvote_cnt AS REAL) / NULLIF(comment_cnt, 0), 1) AS vote_per_comment FROM posts WHERE upvote_cnt >= 10 ORDER BY upvote_cnt DESC;`,
  },
  {
    title: '신규 가입 유저(2024년)',
    track: 'case', domain: 'community', dataset_domain: 'community', chapter_num: null,
    difficulty: 'easy', grading_mode: 'ordered', tags: ['where', 'order_by'],
    description: `2024년 이후 가입한(created_at >= '2024-01-01') 유저의 username, email, reputation, created_at을 조회하세요.\n- created_at 오름차순 정렬`,
    solution_sql: `SELECT username, email, reputation, created_at FROM users WHERE created_at >= '2024-01-01' ORDER BY created_at;`,
  },
  {
    title: '태그별 총 업보트 합산',
    track: 'case', domain: 'community', dataset_domain: 'community', chapter_num: null,
    difficulty: 'medium', grading_mode: 'unordered', tags: ['join', 'group_by', 'sum'],
    description: `tags, post_tags, posts를 조인하여 태그별 총 업보트(total_upvotes)를 조회하세요.\n- total_upvotes 내림차순 정렬`,
    solution_sql: `SELECT t.name, SUM(p.upvote_cnt) AS total_upvotes FROM tags t JOIN post_tags pt ON t.id = pt.tag_id JOIN posts p ON pt.post_id = p.id GROUP BY t.id, t.name ORDER BY total_upvotes DESC;`,
  },
  {
    title: '카테고리별 평균 댓글 수',
    track: 'case', domain: 'community', dataset_domain: 'community', chapter_num: null,
    difficulty: 'easy', grading_mode: 'unordered', tags: ['group_by', 'avg'],
    description: `posts 테이블에서 category별 평균 댓글 수(avg_comments)를 조회하세요.\n- avg_comments 내림차순 정렬`,
    solution_sql: `SELECT category, ROUND(AVG(comment_cnt), 1) AS avg_comments FROM posts GROUP BY category ORDER BY avg_comments DESC;`,
  },
  {
    title: '팔로우 없는 유저',
    track: 'case', domain: 'community', dataset_domain: 'community', chapter_num: null,
    difficulty: 'medium', grading_mode: 'unordered', tags: ['left_join', 'null'],
    description: `다른 유저를 팔로우하지 않은 유저의 username과 reputation을 조회하세요.\n- reputation 내림차순 정렬`,
    solution_sql: `SELECT u.username, u.reputation FROM users u LEFT JOIN follows f ON u.id = f.follower_id WHERE f.follower_id IS NULL ORDER BY u.reputation DESC;`,
  },
  {
    title: '상위 업보트 댓글 TOP 10',
    track: 'case', domain: 'community', dataset_domain: 'community', chapter_num: null,
    difficulty: 'medium', grading_mode: 'ordered', tags: ['join', 'order_by', 'limit'],
    description: `upvote_cnt 기준 TOP 10 댓글의 내용(content), 업보트(upvote_cnt), 작성자(username), 게시글 제목(post_title)을 조회하세요.`,
    solution_sql: `SELECT c.content, c.upvote_cnt, u.username, p.title AS post_title FROM comments c JOIN users u ON c.user_id = u.id JOIN posts p ON c.post_id = p.id ORDER BY c.upvote_cnt DESC LIMIT 10;`,
  },
  {
    title: '최근 일주일 게시글',
    track: 'case', domain: 'community', dataset_domain: 'community', chapter_num: null,
    difficulty: 'easy', grading_mode: 'ordered', tags: ['join', 'where'],
    description: `created_at이 '2024-03-14' 이후인 게시글의 title, category, 작성자(username), created_at을 조회하세요.\n- created_at 내림차순 정렬`,
    solution_sql: `SELECT p.title, p.category, u.username, p.created_at FROM posts p JOIN users u ON p.user_id = u.id WHERE p.created_at >= '2024-03-14' ORDER BY p.created_at DESC;`,
  },
  {
    title: 'Q&A 응답률',
    track: 'case', domain: 'community', dataset_domain: 'community', chapter_num: null,
    difficulty: 'medium', grading_mode: 'unordered', tags: ['case', 'arithmetic'],
    description: `category = 'Q&A'인 게시글 중 comment_cnt > 0인 게시글 비율(response_rate_pct)을 조회하세요.\n- total_qa, answered, response_rate_pct 형식으로 출력`,
    solution_sql: `SELECT COUNT(*) AS total_qa, SUM(CASE WHEN comment_cnt > 0 THEN 1 ELSE 0 END) AS answered, ROUND(SUM(CASE WHEN comment_cnt > 0 THEN 1 ELSE 0 END) * 100.0 / COUNT(*), 1) AS response_rate_pct FROM posts WHERE category = 'Q&A';`,
  },
  {
    title: '가장 많은 태그가 달린 게시글 TOP 5',
    track: 'case', domain: 'community', dataset_domain: 'community', chapter_num: null,
    difficulty: 'medium', grading_mode: 'ordered', tags: ['join', 'group_by', 'order_by'],
    description: `게시글별 태그 수(tag_cnt)를 집계하여 TOP 5의 title과 tag_cnt를 조회하세요.`,
    solution_sql: `SELECT p.title, COUNT(pt.tag_id) AS tag_cnt FROM posts p JOIN post_tags pt ON p.id = pt.post_id GROUP BY p.id, p.title ORDER BY tag_cnt DESC LIMIT 5;`,
  },
  {
    title: '댓글 달지 않은 유저',
    track: 'case', domain: 'community', dataset_domain: 'community', chapter_num: null,
    difficulty: 'medium', grading_mode: 'unordered', tags: ['left_join', 'null'],
    description: `댓글을 한 번도 작성하지 않은 유저의 username과 reputation을 조회하세요.\n- reputation 내림차순 정렬`,
    solution_sql: `SELECT u.username, u.reputation FROM users u LEFT JOIN comments c ON u.id = c.user_id WHERE c.id IS NULL ORDER BY u.reputation DESC;`,
  },
  {
    title: '각 카테고리 최다 조회 게시글',
    track: 'case', domain: 'community', dataset_domain: 'community', chapter_num: null,
    difficulty: 'hard', grading_mode: 'unordered', tags: ['window', 'rank', 'join'],
    description: `카테고리별로 view_cnt가 가장 높은 게시글 1개씩의 title, category, view_cnt, 작성자(username)를 조회하세요.\n- RANK() 윈도우 함수 활용`,
    solution_sql: `WITH ranked AS (SELECT p.title, p.category, p.view_cnt, u.username, RANK() OVER (PARTITION BY p.category ORDER BY p.view_cnt DESC) AS rnk FROM posts p JOIN users u ON p.user_id = u.id) SELECT title, category, view_cnt, username FROM ranked WHERE rnk = 1 ORDER BY view_cnt DESC;`,
  },
  {
    title: '월별 게시글 작성 추이',
    track: 'case', domain: 'community', dataset_domain: 'community', chapter_num: null,
    difficulty: 'easy', grading_mode: 'ordered', tags: ['group_by', 'date'],
    description: `posts 테이블에서 연도-월별 게시글 수(post_cnt)를 조회하세요.\n- 최신 월 순 정렬`,
    solution_sql: `SELECT STRFTIME('%Y-%m', created_at) AS month, COUNT(*) AS post_cnt FROM posts GROUP BY month ORDER BY month DESC;`,
  },
  {
    title: '게시글 수 대비 팔로워 현황',
    track: 'case', domain: 'community', dataset_domain: 'community', chapter_num: null,
    difficulty: 'hard', grading_mode: 'unordered', tags: ['join', 'group_by'],
    description: `게시글을 1개 이상 작성한 유저의 username, 게시글 수(post_cnt), 팔로워 수(follower_cnt)를 조회하세요.\n- follower_cnt 내림차순 정렬`,
    solution_sql: `SELECT u.username, COUNT(DISTINCT p.id) AS post_cnt, COUNT(DISTINCT f.follower_id) AS follower_cnt FROM users u LEFT JOIN posts p ON u.id = p.user_id LEFT JOIN follows f ON u.id = f.following_id GROUP BY u.id, u.username HAVING COUNT(DISTINCT p.id) > 0 ORDER BY follower_cnt DESC;`,
  },
  {
    title: '팔로우/팔로워 동시 현황',
    track: 'case', domain: 'community', dataset_domain: 'community', chapter_num: null,
    difficulty: 'hard', grading_mode: 'unordered', tags: ['join', 'group_by'],
    description: `유저별 팔로우 수(following_cnt)와 팔로워 수(follower_cnt)를 함께 조회하세요.\n- username, following_cnt, follower_cnt 출력\n- follower_cnt 내림차순 정렬`,
    solution_sql: `SELECT u.username, COUNT(DISTINCT f1.following_id) AS following_cnt, COUNT(DISTINCT f2.follower_id) AS follower_cnt FROM users u LEFT JOIN follows f1 ON u.id = f1.follower_id LEFT JOIN follows f2 ON u.id = f2.following_id GROUP BY u.id, u.username ORDER BY follower_cnt DESC;`,
  },
]
